### ISSUE TITLE
Singularity support available?

### ISSUE THREAD

**Issue by titansmc** [bdevans/chaste-docker#12]
Hi guys,
I have some users starting to use your framework but running it on our HPC cluster through Singularity. So far I am creating Singularity recipes based on your docker image, but it could be nice if you provide singularity support.
Thanks.

**Comment by bdevans** [comment]
Hi,

Thanks for you interest and apologies for the delay (this repository is deprecated as the Docker image has now moved into the Chaste organisation: https://github.com/Chaste/chaste-docker). 

I haven't used singularity but am happy to discuss what would need to be done to support it if that would still be useful. Please could you open an issue at the new home (https://github.com/Chaste/chaste-docker) where more people can take a look?
Thanks,

Ben

**Comment by davidbenncsiro** [comment]
I am now using singularity with the docker chaste image. Also happy to be involved in such discussion and/or pooling of recipes.

**Comment by bdevans** [comment]
Thanks for your interest and offer of help. I've opened a new issue at the new home for the this project: https://github.com/Chaste/chaste-docker/issues/4
